force-app/main/default/objects/SapVistexAgreement__c/SapVistexAgreement__c.object-meta.xml
<CustomObject>
    <label>Pricing Agreements</label>
    <nameField>
        <label>Pricing Agreements</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SapVistexAgreement__c/fields/DirectAccountLookup__c.field-meta.xml
<CustomField>
    <fullName>DirectAccountLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Purchaser Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pricing Agreements</relationshipLabel>
    <relationshipName>Pricing_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SapVistexAgreement__c/fields/IndirectAccountLookup__c.field-meta.xml
<CustomField>
    <fullName>IndirectAccountLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pricing Agreements (Customer Name)</relationshipLabel>
    <relationshipName>Pricing_Agreements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPA_Request__c/SPA_Request__c.object-meta.xml
<CustomObject>
    <label>SPA Request</label>
    <nameField>
        <displayFormat>S-{000000}-{YY}-{MM}-{DD}</displayFormat>
        <label>PA Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPA Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPA_Request__c/fields/Bill_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Purchaser</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SPA Requests (Primary Purchaser)</relationshipLabel>
    <relationshipName>SPA_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPA_Request__c/fields/Quote_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_To_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SPA Requests (Customer)</relationshipLabel>
    <relationshipName>SPA_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPA_Request__c/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <description>SAPR-1080</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Benefit Request</fullName>
            </value>
            <value>
                <fullName>Relationship Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPA_Request__c/fields/SapAgreementNumber__c.field-meta.xml
<CustomField>
    <fullName>SapAgreementNumber__c</fullName>
    <label>SAP Agreement Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPA_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted for Authorization</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Not Authorized</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/SPA_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <label>SPA Request Line Item</label>
    <nameField>
        <displayFormat>LIN-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPA Request Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/AME_Indicator__c.field-meta.xml
<CustomField>
    <fullName>AME_Indicator__c</fullName>
    <description>Add, Modify, Expire Indicator, Making it restricted as per SASER-10336</description>
    <label>AME Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>Add</fullName>
                <isActive>false</isActive>
                <label>Add</label>
            </value>
            <value>
                <fullName>Expire</fullName>
                <isActive>false</isActive>
                <label>Expire</label>
            </value>
            <value>
                <fullName>Modify</fullName>
                <isActive>false</isActive>
                <label>Modify</label>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Code__c</fullName>
    <label>Item Code</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <label>Item Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/Requested_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_Expiration_Date__c</fullName>
    <label>Requested Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/Requested_Net_Multiplier_Rebate__c.field-meta.xml
<CustomField>
    <fullName>Requested_Net_Multiplier_Rebate__c</fullName>
    <label>Requested Net Multiplier Rebate</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/Requested_Net_Price_Rebate__c.field-meta.xml
<CustomField>
    <fullName>Requested_Net_Price_Rebate__c</fullName>
    <label>Requested Net Price Rebate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/SPA_Request__c.field-meta.xml
<CustomField>
    <fullName>SPA_Request__c</fullName>
    <label>SPA Request</label>
    <referenceTo>SPA_Request__c</referenceTo>
    <relationshipLabel>SPA Request Line Item</relationshipLabel>
    <relationshipName>SPA_Request_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BenefitRequestController.cls
public with sharing class BenefitRequestController {
    @InvocableMethod(label='Create Benefit Request' description='Get Agreement Number and create Benefit Request.')
    public static List<ResponseOutput> createBenefitRequest(List<RequestInput> inputs) {        
        RequestInput input = inputs[0];       
        Map<String,String> result = doValidationAndCreateBenefitRequest(input);
        ResponseOutput output = new ResponseOutput();
        String baseUrl = 'https://orgfarm-8ad19981fe-dev-ed.develop.lightning.force.com';
        if(result.get('Success') != null) {
            output.Prompt = '<b><span style="color:green;">SPA Request created successfully.</span></b><br/><a href="' + baseUrl + '/' + result.get('Success') + '" target="_blank">View Request</a>';
            output.newRequestId = Id.valueOf(result.get('Success'));
        } else if (result.get('Error') != null) {
            output.Prompt = '<b><span style="color:red;">' + result.get('Error') + '</span></b><br/><a href="' + baseUrl + '/' + result.get('Active_Request') + '" target="_blank">'+result.get('Name')+'</a>';
            output.newRequestId = Id.valueOf(result.get('Active_Request'));
        }
        return new List<ResponseOutput>{output};
    }

    private static Map<String,String> doValidationAndCreateBenefitRequest(RequestInput input) {
        Map<String,String> result = new Map<String,String>();        
        List<Id> createdIds = new List<Id>();
        //blank check
        if (String.isBlank(input.SapAgreementNumber)) {
            result.put('Error','Agreement number is required for Benefit Request.');
            return result;
        }
        // Check if agreement exists
        List<SapVistexAgreement__c> agreements = [
            SELECT Id,DirectAccountLookup__c,IndirectAccountLookup__c FROM SapVistexAgreement__c WHERE SapAgreementNumber__c = :input.SapAgreementNumber LIMIT 1
        ];
        if (agreements.isEmpty()) {
            result.put('Error','No Related Agreement found for the provided SAP Agreement Number.');
            return result;
        }

        // Check for open SPA Request for this agreement
        List<Spa_Request__c> openRequests = [
            SELECT Id,Name FROM Spa_Request__c 
            WHERE SapAgreementNumber__c = :input.SapAgreementNumber 
            AND Status__c IN ('Draft','Submitted for Authorization','Authorized','Acknowledged') LIMIT 1
        ];
        if (!openRequests.isEmpty()) {
            result.put('Error','Active Request already exists for this Agreement.');
            result.put('Active_Request',openRequests[0].Id);
            result.put('Name',openRequests[0].Name);
            return result;
        }
        // Create SPA Request
        Spa_Request__c newRequest = new Spa_Request__c();
        newRequest.RequestType__c = 'Benefit Request';
        newRequest.SapAgreementNumber__c = input.SapAgreementNumber;
        newRequest.Bill_To_Name__c = agreements[0].DirectAccountLookup__c;
        newRequest.Quote_To_Name__c = agreements[0].IndirectAccountLookup__c;
        newRequest.Status__c = 'Draft';
        insert newRequest;
        result.put('Success',newRequest.Id);
        result.put('Name',newRequest.Name);

        if(input.lines == null || input.lines.isEmpty()) {
            result.put('Error','At least one Benefit Line Item is required.');
            return result;
        }
        List<Spa_Request_Line_Item__c> lineItems = new List<Spa_Request_Line_Item__c>();
        for(BenefitRequestInput lineItem : input.lines) {
            if (String.isBlank(lineItem.ItemCode) || lineItem.ListPrice == null || String.isBlank(lineItem.Operation)) {
                result.put('Error','Item Code, List Price and Operation are required for each Benefit Line Item.');
                return result;
            }
            if (lineItem.Operation != 'Add' && lineItem.Operation != 'Modify' && lineItem.Operation != 'Expire') {
                result.put('Error','Invalid Operation. Use "Add", "Modify" or "Expire".');
                return result;
            }
            lineItems.add(createSpaRequestLineItems(lineItem, newRequest.Id));          
        }
        if (lineItems.isEmpty()) {
            result.put('Error','No valid line items to create.');
            return result;
        }
        insert lineItems;
        //createSpaRequestLineItems(newRequest.Id);    
        return result;
    }

    private static Spa_Request_Line_Item__c createSpaRequestLineItems(BenefitRequestInput input, Id requestId) {
        //List<Spa_Request_Line_Item__c> lineItems = new List<Spa_Request_Line_Item__c>();
        Spa_Request_Line_Item__c newLineItem = new Spa_Request_Line_Item__c();
        newLineItem.Spa_Request__c = requestId;
        newLineItem.Item_Code__c = input.ItemCode;
        newLineItem.Item_Description__c = 'Benefit Request Item';
        newLineItem.Unit_List_Price__c = Decimal.valueOf(input.ListPrice);
        //newLineItem.Requested_Net_Multiplier_Rebate__c = 0.0; // Set appropriate values
        newLineItem.AME_Indicator__c = input.Operation=='Add' ? 'A' : input.Operation=='Modify' ? 'M' : 'E';
        //newLineItem.Requested_Net_Price_Rebate__c = 0.0; // Set appropriate values
        newLineItem.Requested_Expiration_Date__c = input.ExpirationDate;
        //lineItems.add(newLineItem);
        //insert newLineItem;
        return newLineItem;
    }

    public class RequestInput{
        @InvocableVariable(label='Agreement Number' required=true)
        public String SapAgreementNumber;
        @InvocableVariable(label='Benefit Lines' required=true)
        public List<BenefitRequestInput> lines;
    }
    
    public class BenefitRequestInput {
        @InvocableVariable(label='Item Code' required=true)
        public String ItemCode;
        @InvocableVariable(label='List Price' required=true)
        public String ListPrice;
        @InvocableVariable(description='Add/Modify/Expire' required=true)
        public String Operation;
        @InvocableVariable(label='Requested Expiration Date')
        public Date ExpirationDate;
    }

    public class ResponseOutput {
        @InvocableVariable
        public String Prompt;
        @InvocableVariable
        public Id newRequestId;
    }    
}