force-app/main/default/objects/SapVistexAgreement__c/SapVistexAgreement__c.object-meta.xml
<CustomObject>
    <label>Pricing Agreements</label>
    <nameField>
        <label>Pricing Agreements</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Agreements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SapVistexAgreement__c/fields/DirectAccountLookup__c.field-meta.xml
<CustomField>
    <fullName>DirectAccountLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Purchaser Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pricing Agreements</relationshipLabel>
    <relationshipName>Pricing_Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SapVistexAgreement__c/fields/IndirectAccountLookup__c.field-meta.xml
<CustomField>
    <fullName>IndirectAccountLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pricing Agreements (Customer Name)</relationshipLabel>
    <relationshipName>Pricing_Agreements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPA_Request__c/SPA_Request__c.object-meta.xml
<CustomObject>
    <label>SPA Request</label>
    <nameField>
        <displayFormat>S-{000000}-{YY}-{MM}-{DD}</displayFormat>
        <label>PA Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPA Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPA_Request__c/fields/Bill_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Purchaser</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SPA Requests (Primary Purchaser)</relationshipLabel>
    <relationshipName>SPA_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPA_Request__c/fields/Quote_To_Name__c.field-meta.xml
<CustomField>
    <fullName>Quote_To_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SPA Requests (Customer)</relationshipLabel>
    <relationshipName>SPA_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SPA_Request__c/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <description>SAPR-1080</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Benefit Request</fullName>
            </value>
            <value>
                <fullName>Relationship Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPA_Request__c/fields/SapAgreementNumber__c.field-meta.xml
<CustomField>
    <fullName>SapAgreementNumber__c</fullName>
    <label>SAP Agreement Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPA_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted for Authorization</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Not Authorized</fullName>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Finalized</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SpaRequestEligibility__c/SpaRequestEligibility__c.object-meta.xml
<CustomObject>
    <label>SPA Request Eligibility</label>
    <nameField>
        <displayFormat>SRE-{0000}</displayFormat>
        <label>SPA Request Eligibility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPA Request Eligibilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SpaRequestEligibility__c/fields/AEIndicator__c.field-meta.xml
<CustomField>
    <fullName>AEIndicator__c</fullName>
    <label>AE Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SpaRequestEligibility__c/fields/DirectAccount__c.field-meta.xml
<CustomField>
    <fullName>DirectAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Direct Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SPA Request Eligibilities</relationshipLabel>
    <relationshipName>SPA_Request_Eligibilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SpaRequestEligibility__c/fields/EligibilityEffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EligibilityEffectiveDate__c</fullName>
    <label>Eligibility Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SpaRequestEligibility__c/fields/EligibilityExpireDate__c.field-meta.xml
<CustomField>
    <fullName>EligibilityExpireDate__c</fullName>
    <label>Eligibility Expire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SpaRequestEligibility__c/fields/IndirectAccount__c.field-meta.xml
<CustomField>
    <fullName>IndirectAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Indirect Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SPA Request Eligibilities (Indirect Account)</relationshipLabel>
    <relationshipName>SPA_Request_Eligibilities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SpaRequestEligibility__c/fields/SapAgreementNumber__c.field-meta.xml
<CustomField>
    <fullName>SapAgreementNumber__c</fullName>
    <label>Sap Agreement Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpaRequestEligibility__c/fields/SPARequest__c.field-meta.xml
<CustomField>
    <fullName>SPARequest__c</fullName>
    <label>SPA Request</label>
    <referenceTo>SPA_Request__c</referenceTo>
    <relationshipLabel>SPA Request Eligibilities</relationshipLabel>
    <relationshipName>SPA_Request_Eligibilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RelationshipRequestController.cls
public with sharing class RelationshipRequestController {
    @InvocableMethod(label='Create Relationship Request' description='Get Agreement Number and create Relationship Request.')
    public static List<ResponseOutput> createRelationshipRequest(List<RelationshipRequestInput> inputs) {        
        RelationshipRequestInput input = inputs[0];       
        Map<String,String> result = doValidationAndCreateRelationshipRequest(input);
        ResponseOutput output = new ResponseOutput();
        if(result.get('Success') != null) {
            output.Prompt = 'SPA Request created successfully.';
            output.newRequestId = Id.valueOf(result.get('Success'));
        } else if (result.get('Error') != null) {
            output.Prompt = result.get('Error');
            output.newRequestId = null;
        }
        return new List<ResponseOutput>{output};
    }

    private static Map<String,String> doValidationAndCreateRelationshipRequest(RelationshipRequestInput input) {
        Map<String,String> result = new Map<String,String>();        
        List<Id> createdIds = new List<Id>();
        //blank check
        if (String.isBlank(input.SapAgreementNumber)) {
            result.put('Error','Agreement number is required for Benefit Request.');
            return result;
        }
        // Check if agreement exists
        List<SapVistexAgreement__c> agreements = [
            SELECT Id,DirectAccountLookup__c,IndirectAccountLookup__c FROM SapVistexAgreement__c WHERE SapAgreementNumber__c = :input.SapAgreementNumber LIMIT 1
        ];
        if (agreements.isEmpty()) {
            result.put('Error','No Related Agreement found for the provided SAP Agreement Number.');
            return result;
        }

        if(input.DirectAccountId == null && input.InDirectAccountId == null) {
            result.put('Error','Direct or Indirect Account Ids are required for Relationship Request.');
            return result;
        }

        if(input.Operation == 'Expire') {
            for(SapVistexAgreement__c agreement : agreements) {
                if(agreement.DirectAccountLookup__c == input.DirectAccountId && agreement.IndirectAccountLookup__c == input.InDirectAccountId) {
                    break;//combination found
                } else{
                    result.put('Error','No Agreement found for the provided Direct and Indirect Account combination.');
                    return result;
                }
            }
        } else if(input.Operation == 'Add') {
            // Check if agreement exists for account combination
            List<SapVistexAgreement__c> existingAgreements = [
                SELECT Id,DirectAccountLookup__c,IndirectAccountLookup__c FROM SapVistexAgreement__c 
                WHERE DirectAccountLookup__c = :input.DirectAccountId 
                AND IndirectAccountLookup__c = : input.InDirectAccountId LIMIT 1
            ];
            if (!existingAgreements.isEmpty()) {
                result.put('Error','No Related Agreement found for the provided SAP Agreement Number.');
                return result;
            }
        } else {
            result.put('Error','Invalid Operation. Use "Expire" or "Add".');
            return result;
        }

        // Create SPA Request for Relationship Request
        Spa_Request__c newRequest = new Spa_Request__c();
        newRequest.RequestType__c = 'Relationship Request';
        newRequest.SapAgreementNumber__c = input.SapAgreementNumber;
        newRequest.Bill_To_Name__c = input.DirectAccountId;   
        newRequest.Quote_To_Name__c = input.InDirectAccountId;
        newRequest.Status__c = 'Draft';
        insert newRequest;

        SpaRequestEligibility__c eligibility = new SpaRequestEligibility__c();
        eligibility.SPARequest__c = newRequest.Id;
        eligibility.DirectAccount__c = input.DirectAccountId;  
        eligibility.IndirectAccount__c = input.InDirectAccountId;
        eligibility.SapAgreementNumber__c = input.SapAgreementNumber;
        eligibility.AEIndicator__c = input.Operation== 'Add' ? 'A' : 'E';
        if(input.Operation == 'Expire') {
            eligibility.EligibilityExpireDate__c = Date.today();
        } else {
            eligibility.EligibilityEffectiveDate__c = Date.today();
        }
        insert eligibility;
        result.put('Success',newRequest.Id);
        return result;
    }

    public class RelationshipRequestInput {
        @InvocableVariable(required=true)
        public String SapAgreementNumber;
        @InvocableVariable(label='Direct Account Name' required=true)
        public String DirectAccountId;
        @InvocableVariable(label='Indirect Account Name')
        public String InDirectAccountId;
        @InvocableVariable(description='Expire or Add' required=true)
        public String Operation;
    }

    public class ResponseOutput {
        @InvocableVariable
        public String Prompt;
        @InvocableVariable
        public Id newRequestId;
    }
}