force-app/main/default/objects/Approval_History__c/Approval_History__c.object-meta.xml
<CustomObject>
    <label>Approval History</label>
    <nameField>
        <label>Approval History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approval Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Approval_History__c/fields/Ad_Hoc_Price_Status__c.field-meta.xml
<CustomField>
    <fullName>Ad_Hoc_Price_Status__c</fullName>
    <label>Ad Hoc Price Status</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/PDCAT__c.field-meta.xml
<CustomField>
    <fullName>PDCAT__c</fullName>
    <label>PDCAT</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Approval_History__c/fields/Unit_List_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_List_Price__c</fullName>
    <label>Unit List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Price_Manager_Page_Events__e/Price_Manager_Page_Events__e.object-meta.xml
<CustomObject>
    <label>Price Manager Page Event</label>
    <pluralLabel>Price Manager Page Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Approval_HistoryController.cls
public without sharing class Approval_HistoryController {
    @AuraEnabled(cacheable=true)
    public static List<Approval_History__c> getAdhocApprovalHistory(Id quoteId) {
        return [
            SELECT Id, Line_Item_Number__c, Product_Description__c, Quantity__c, PDCAT__c, Ad_Hoc_Price_Status__c, Unit_List_Price__c
            FROM Approval_History__c
            WHERE Quote__c = :quoteId
              AND Ad_Hoc_Price_Status__c != null
        ];
    }

    @InvocableMethod(label='Approve Adhoc Approval Histories' description='Approve Adhoc Approval Histories' category='Approval_History__c')
    public static List<String> approveAdhocApprovalHistories(List<AccountSummaryRequest> requests) {
        AccountSummaryRequest req = requests[0];
        List<approval_history__c> approvalHistories = new List<approval_history__c>();
        for(Id adhocApprovalHistoryId : req.adhocApprovalHistoryIds) {
            approvalHistories.add(new  Approval_History__c(Id=adhocApprovalHistoryId,Ad_Hoc_Price_Status__c = 'Authorized'));
        }
        update approvalHistories;
        Price_Manager_Page_Events__e myEvent = new Price_Manager_Page_Events__e(
            Record_Id__c = req.adhocApprovalHistoryIds[0],
            Message__c = 'Adhoc Approval Histories Approved'
        );
        Database.SaveResult results = EventBus.publish(myEvent);
        return new List<String>{'A communication Stream Record has been added with the Reason you have Provided and Quote has been marked as "Not Authorized"'};
    }

    public class AccountSummaryRequest {
        @InvocableVariable(label='AdhocApprovalHistoryIds' description='The ID of Adhoc Approval History records' required=true)
        public List<Id> adhocApprovalHistoryIds;
    }
}