force-app/main/default/objects/SpaRequestEligibility__c/SpaRequestEligibility__c.object-meta.xml
<CustomObject>
    <label>SPA Request Eligibility</label>
    <nameField>
        <displayFormat>SRE-{0000}</displayFormat>
        <label>SPA Request Eligibility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPA Request Eligibilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SpaRequestEligibility__c/fields/AEIndicator__c.field-meta.xml
<CustomField>
    <fullName>AEIndicator__c</fullName>
    <label>AE Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Value1</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SpaRequestEligibility__c/fields/DirectAccount__c.field-meta.xml
<CustomField>
    <fullName>DirectAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Direct Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SPA Request Eligibilities</relationshipLabel>
    <relationshipName>SPA_Request_Eligibilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SpaRequestEligibility__c/fields/EligibilityEffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EligibilityEffectiveDate__c</fullName>
    <label>Eligibility Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SpaRequestEligibility__c/fields/EligibilityExpireDate__c.field-meta.xml
<CustomField>
    <fullName>EligibilityExpireDate__c</fullName>
    <label>Eligibility Expire Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SpaRequestEligibility__c/fields/IndirectAccount__c.field-meta.xml
<CustomField>
    <fullName>IndirectAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Indirect Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SPA Request Eligibilities (Indirect Account)</relationshipLabel>
    <relationshipName>SPA_Request_Eligibilities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SpaRequestEligibility__c/fields/SapAgreementNumber__c.field-meta.xml
<CustomField>
    <fullName>SapAgreementNumber__c</fullName>
    <label>Sap Agreement Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpaRequestEligibility__c/fields/SPARequest__c.field-meta.xml
<CustomField>
    <fullName>SPARequest__c</fullName>
    <label>SPA Request</label>
    <referenceTo>SPA_Request__c</referenceTo>
    <relationshipLabel>SPA Request Eligibilities</relationshipLabel>
    <relationshipName>SPA_Request_Eligibilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SpaRequestEligibilityGridController.cls
public with sharing class SpaRequestEligibilityGridController {
    @AuraEnabled(cacheable=true)
    public static List<SpaRequestEligibility__c> getSpaRequestEligibilities(Id parentId) {
        if (parentId == null) {
            return new List<SpaRequestEligibility__c>();
        }
        return [
            SELECT Id, SapAgreementNumber__c, DirectAccount__c, DirectAccount__r.Name, IndirectAccount__c, 
            IndirectAccount__r.Name, AEIndicator__c,EligibilityEffectiveDate__c,  EligibilityExpireDate__c
            FROM SpaRequestEligibility__c
            WHERE SPARequest__c = :parentId
        ];
    }
}