force-app/main/default/objects/Communication_Stream__c/Communication_Stream__c.object-meta.xml
<CustomObject>
    <description>Created for US# 291,292,293,294</description>
    <label>Communication Stream</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Communication Stream Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Streams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Communication_Stream__c/fields/Commented_By__c.field-meta.xml
<CustomField>
    <fullName>Commented_By__c</fullName>
    <description>Contain the name of user who commented on communication stream. US#-CPQPDAQ-4</description>
    <label>Commented By</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Communication_Stream__c/fields/Quote_ID__c.field-meta.xml
<CustomField>
    <fullName>Quote_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Communication Streams</relationshipLabel>
    <relationshipName>Communication_Streams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PI_Deal_History2__c/PI_Deal_History2__c.object-meta.xml
<CustomObject>
    <label>PI Deal History2</label>
    <nameField>
        <label>PI Deal History2</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PI Deal History2s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PI_Deal_History2__c/fields/Line_cur_AuthorizedPrice__c.field-meta.xml
<CustomField>
    <fullName>Line_cur_AuthorizedPrice__c</fullName>
    <label>Line_cur_AuthorizedPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PI_Deal_History2__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <label>Line_Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PI_Deal_History2__c/fields/Quote_Rev__c.field-meta.xml
<CustomField>
    <fullName>Quote_Rev__c</fullName>
    <label>Quote_Rev</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CommunicationStreamController.cls
public without sharing class CommunicationStreamController {
    public class CommStreamWrapper {
        @AuraEnabled public Id Id;
        @AuraEnabled public String Name;
        @AuraEnabled public String Note;
        @AuraEnabled public String Category;
        @AuraEnabled public String CommentedBy;
        @AuraEnabled public String CreatedByName;
        @AuraEnabled public DateTime CreatedDate;
        public CommStreamWrapper(Communication_Stream__c comm) {
            Id = comm.Id;
            Name = comm.Name;
            Note = comm.Note__c;
            Category = comm.Category__c;
            CommentedBy = comm.Commented_By__c;
            CreatedByName = comm.CreatedBy != null ? comm.CreatedBy.Name : null;
            CreatedDate = comm.CreatedDate;
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<CommStreamWrapper> getRecordsComm(Id quoteId) {
        List<Communication_Stream__c> comms = [SELECT Id, Name, Note__c, Category__c, Commented_By__c, CreatedDate, CreatedBy.Name FROM Communication_Stream__c WHERE Quote_ID__c = :quoteId ORDER BY CreatedDate DESC];
        List<CommStreamWrapper> wrappers = new List<CommStreamWrapper>();
        for (Communication_Stream__c comm : comms) {
            wrappers.add(new CommStreamWrapper(comm));
        }
        return wrappers;
    }

    @InvocableMethod(label='Get Line Previous Value' description='Get Line Previous Value' category='PI_Deal_History2__c')
    public static List<PI_Deal_History2__c> getLinePrevVal(List<AccountSummaryRequestForLine> requests) {
        return [select id,Line_cur_AuthorizedPrice__c,Quote_Rev__c,Line_Number__c from PI_Deal_History2__c where Line_Number__c = :requests[0].LineNumber and Quote_Rev__c = :Decimal.valueOf(requests[0].SpdRev)];
    }

    public class AccountSummaryRequestForLine {
        @InvocableVariable(label='LineNumber' description='The number of the line' required=true)
        public String LineNumber;
        @InvocableVariable(label='SpdRev' description='The SpdRev' required=true)
        public String SpdRev;
    }
}