force-app/main/default/objects/SPA_Request__c/SPA_Request__c.object-meta.xml
<CustomObject>
    <label>SPA Request</label>
    <nameField>
        <displayFormat>S-{000000}-{YY}-{MM}-{DD}</displayFormat>
        <label>PA Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPA Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPA_Request_Line_Item__c/SPA_Request_Line_Item__c.object-meta.xml
<CustomObject>
    <label>SPA Request Line Item</label>
    <nameField>
        <displayFormat>LIN-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPA Request Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/AME_Indicator__c.field-meta.xml
<CustomField>
    <fullName>AME_Indicator__c</fullName>
    <description>Add, Modify, Expire Indicator, Making it restricted as per SASER-10336</description>
    <label>AME Indicator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>Add</fullName>
                <isActive>false</isActive>
                <label>Add</label>
            </value>
            <value>
                <fullName>Expire</fullName>
                <isActive>false</isActive>
                <label>Expire</label>
            </value>
            <value>
                <fullName>Modify</fullName>
                <isActive>false</isActive>
                <label>Modify</label>
            </value>
            <value>
                <fullName>Value1</fullName>
                <isActive>false</isActive>
                <label>Value1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/Item_Code__c.field-meta.xml
<CustomField>
    <fullName>Item_Code__c</fullName>
    <label>Item Code</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Item_Description__c</fullName>
    <label>Item Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/ProfileMultiplier__c.field-meta.xml
<CustomField>
    <fullName>ProfileMultiplier__c</fullName>
    <label>Profile Multiplier</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/Requested_Net_Multiplier_Rebate__c.field-meta.xml
<CustomField>
    <fullName>Requested_Net_Multiplier_Rebate__c</fullName>
    <label>Requested Net Multiplier Rebate</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/Requested_Net_Price_Rebate__c.field-meta.xml
<CustomField>
    <fullName>Requested_Net_Price_Rebate__c</fullName>
    <label>Requested Net Price Rebate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/SPA_Request__c.field-meta.xml
<CustomField>
    <fullName>SPA_Request__c</fullName>
    <label>SPA Request</label>
    <referenceTo>SPA_Request__c</referenceTo>
    <relationshipLabel>SPA Request Line Item</relationshipLabel>
    <relationshipName>SPA_Request_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/Unit_Book_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Book_Price__c</fullName>
    <label>Unit Book Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SPA_Request_Line_Item__c/fields/Unit_Profile_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Profile_Price__c</fullName>
    <label>Unit Profile Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SpaRequestLineItemsGridController.cls
public with sharing class SpaRequestLineItemsGridController {
    @AuraEnabled(cacheable=true)
    public static List<SPA_Request_Line_Item__c> getSpaRequestLineItems(Id parentId) {
        if (parentId == null) {
            return new List<SPA_Request_Line_Item__c>();
        }
        return [
            SELECT Id, Item_Code__c, Item_Description__c, Unit_Book_Price__c, Unit_Profile_Price__c, ProfileMultiplier__c, Requested_Net_Multiplier_Rebate__c, AME_Indicator__c, Requested_Net_Price_Rebate__c
            FROM SPA_Request_Line_Item__c
            WHERE Spa_Request__c = :parentId
        ];
    }
}